name: CI
on:
  workflow_dispatch:
  
jobs:
  test-ios:
    name: iOS (aarch64)
    runs-on: macos-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Checkout C3 Repository
        uses: actions/checkout@v6
        with:
          repository: c3lang/c3c
          path: c3c
          
      - name: Build CMake (Release)
        run: |
          cmake -S c3c -B build-release -G Xcode \
           -DCMAKE_SYSTEM_NAME=iOS \
           -DCMAKE_OSX_ARCHITECTURES=arm64 \
           -DCMAKE_BUILD_TYPE=Release \
           -DC3_FETCH_LLVM=ON

          cmake --build build-release --config Release
          
      - name: Build CMake (Debug)
        run: |
            cmake -S c3c -B build-debug -G Xcode \
             -DCMAKE_SYSTEM_NAME=iOS \
             -DCMAKE_OSX_ARCHITECTURES=arm64 \
             -DCMAKE_BUILD_TYPE=Debug \
             -DC3_FETCH_LLVM=ON

            cmake --build build-debug --config Debug
