name: CI
on:
  workflow_dispatch:
  
jobs:
  # test-azl:
  #   name: Azure Linux (x64)
  #   runs-on: ubuntu-24.04
  #   container:
  #     image: mcr.microsoft.com/azurelinux-beta/base/core:4.0
  #   strategy:
  #     fail-fast: false
  #   steps: 
  #     - name: Bootstrap Core System Dependencies
  #       run: |
  #         dnf check-update || true
  #         dnf install -y git tar shadow-utils
        
  #     - uses: actions/checkout@v6
  
  #     - name: Install Development Build Tools
  #       run: |
  #         dnf check-update || true
  #         dnf install -y python3 clang gcc-c++ libcurl-devel meson ninja-build libzstd-devel \
  #                      libX11-devel libXrandr-devel libXinerama-devel libXi-devel \
  #                      libXxf86vm-devel libXcursor-devel
          
  #     - name: Clone C3 Compiler Source
  #       run: git clone --depth=1 https://github.com/Manulinares/c3c -b meson_build_system --single-branch
  
  #     - name: Build Meson (Debug)
  #       run: |
  #         meson setup c3c build-debug --buildtype=debug -Dfetch_llvm=true
  #         meson compile -C build-debug
  
  #     - name: Run Unified Tests
  #       run: ./c3c/scripts/tools/ci_tests.sh "./build-debug/c3c"


  test-emscripten:
    name: Emscripten (x64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: Clone C3 Compiler Source
        run: git clone --depth=1 https://github.com/c3lang/c3c c3c

      - name: Setup Emscripten
        uses: emscripten-core/setup-emsdk@v16
        with:
          version: "latest"
          actions-cache-folder: "emsdk-cache"

      - name: Build static archives
        run: embuilder build libc libdlmalloc libstubs libsockets libclang_rt.builtins

      - name: Build CMake (Debug)
        run: |
          emcmake cmake -S c3c -B build-debug -G Ninja \
            -DCMAKE_BUILD_TYPE=Debug \
            -DC3_FETCH_LLVM=ON \
            -DC3_WITH_LLVM=ON \
            -DC3_LINK_DYNAMIC=OFF \
            -DC3_AVR_DISABLE=ON \
            -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=BOTH \
            -DCMAKE_EXE_LINKER_FLAGS="-sALLOW_MEMORY_GROWTH=1 -sNODERAWFS=1 -sEXIT_RUNTIME=0 -sINITIAL_MEMORY=256MB -sMAXIMUM_MEMORY=8GB -sSTACK_SIZE=8MB -sERROR_ON_UNDEFINED_SYMBOLS=0 -sEXPORTED_RUNTIME_METHODS=FS,callMain -sEXPORTED_FUNCTIONS=_main,_fflush"
          cmake --build build-debug

      - name: Run Unified Tests
        run: |
          echo "--- Running Unit Tests ---"
          node ./build-debug/c3c.js --stdlib "$GITHUB_WORKSPACE/c3c/lib" compile-test "$GITHUB_WORKSPACE/c3c/test/unit" -O1 -D SLOW_TESTS --target emscripten -o unit_tests.js
          node unit_tests.js

          echo "--- Running Examples ---"
          node ./build-debug/c3c.js --stdlib "$GITHUB_WORKSPACE/c3c/lib" compile "$GITHUB_WORKSPACE/c3c/resources/examples/base64.c3" --target emscripten -o base64.js
          node base64.js
          node ./build-debug/c3c.js --stdlib "$GITHUB_WORKSPACE/c3c/lib" compile "$GITHUB_WORKSPACE/c3c/resources/examples/binarydigits.c3" --target emscripten -o binarydigits.js
          node binarydigits.js
          node ./build-debug/c3c.js --stdlib "$GITHUB_WORKSPACE/c3c/lib" compile "$GITHUB_WORKSPACE/c3c/resources/examples/mandelbrot.c3" --target emscripten -o mandelbrot.js
          node mandelbrot.js
          node ./build-debug/c3c.js --stdlib "$GITHUB_WORKSPACE/c3c/lib" compile "$GITHUB_WORKSPACE/c3c/resources/examples/factorial_macro.c3" --target emscripten -o factorial.js
          node factorial.js
          node ./build-debug/c3c.js --stdlib "$GITHUB_WORKSPACE/c3c/lib" compile "$GITHUB_WORKSPACE/c3c/resources/examples/fannkuch-redux.c3" --target emscripten -o fannkuch.js
          node fannkuch.js 8
          node ./build-debug/c3c.js --stdlib "$GITHUB_WORKSPACE/c3c/lib" compile "$GITHUB_WORKSPACE/c3c/resources/examples/spectralnorm.c3" --target emscripten -o spectralnorm.js
          node spectralnorm.js 100
          node ./build-debug/c3c.js --stdlib "$GITHUB_WORKSPACE/c3c/lib" compile "$GITHUB_WORKSPACE/c3c/resources/examples/nbodies.c3" --target emscripten -o nbodies.js
          node nbodies.js 1000
          node ./build-debug/c3c.js --stdlib "$GITHUB_WORKSPACE/c3c/lib" compile "$GITHUB_WORKSPACE/c3c/resources/examples/plus_minus.c3" --target emscripten -o plus_minus.js
          node plus_minus.js 10 + 20 - 5
          node ./build-debug/c3c.js --stdlib "$GITHUB_WORKSPACE/c3c/lib" compile "$GITHUB_WORKSPACE/c3c/resources/examples/fasta.c3" --target emscripten -o fasta.js
          node fasta.js 100
          node ./build-debug/c3c.js --stdlib "$GITHUB_WORKSPACE/c3c/lib" compile "$GITHUB_WORKSPACE/c3c/resources/examples/args.c3" --target emscripten -o args.js
          node args.js -- foo -bar "baz baz"

          echo "--- Running Bare Wasm Test ---"
          node ./build-debug/c3c.js --stdlib "$GITHUB_WORKSPACE/c3c/lib" compile --target wasm32 -g0 --no-entry -Os "$GITHUB_WORKSPACE/c3c/resources/testfragments/wasm4.c3" -o wasm4.wasm
          

          
          

      
          
